### ISSUE TITLE
Create Grid Layout for Gratitude Cards

### ISSUE THREAD

**Issue by VCGithubCode** [VCGithubCode/Gratidudes#64]
Description: Design and implement a visually appealing grid layout to display gratitude cards on the homepage. The grid should be responsive and accommodate varying card sizes gracefully.

**Comment by patrickhladun** [comment]
Implemented the grid layout with a responsive design approach. Cards are now displayed in a single column on mobile devices for optimal viewing and usability. On larger screens, the layout switches to three columns.
